language: go

go:
  - tip
  - 1.6beta1

matrix:
  include:
    - go: 1.5.2
      env: GO15VENDOREXPERIMENT=1
      # HINT: go-1.5.x needs GO15VENDOREXPERIMENT, therefore specify it via "include"
  allow_failures:
    - go: tip
      # HINT: this is only for interest -- decision to support new versions is made manually

install:
  # set up coveralls.io integration
  go get golang.org/x/tools/cmd/cover
  go get github.com/mattn/goveralls

script:
  # enable coveralls.io integration
  go test -v -covermode=count -coverprofile=coverage.out
  $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
